README.md
main.py
utils.py

This adds the arguments for the rpi-rgb-led-matrix library as passable arguments when starting main.py. Helpful for led matrixes that need a little more configuring (gpio slowdown, more columns than the default 32, brightness, etc)

Added the led matrix configuration options to the accepted arguments

---

renderers/standings.py

This just moves things over on the standings screen enough to fit a W or L in the top right of the screen. Tested with 3 digit wins and still works. I really feel like the readability is improved this way. I also tried adding a W/L to the end of each line and it just looked a lot more cluttered (for obvious reasons)

Modify the standings screen to fit a W or L for better readability

---

data/pregame.py
renderers/pregame.py

Some of these nonsense games aren't returning any overview at all. This probably won't be an issue during the regular season but it's probably a good idea to fail more gracefully anyways. I also append an error message after the pitchers scroll but this will rely on #30 for there to be enough time to actually see the message if rotation is enabled.

Manually abbreviate team names when the pregame fails to find an overview

---

renderers/scoreboard.py

Outs were always rendered 1 greater than they actually were

Fix off by one with rendering outs

---

data/bases.py
data/inning.py
data/outs.py
data/pitches.py
data/pregame.py
data/scoreboard.py
data/team.py
renderers/games.py
renderers/pregame.py
renderers/scoreboard.py

Fixes #49 
Fixes #50 
Use overview data for everything. This removes the usage of the nested attributes from the `games` and `game_events` APIs, as it was incredibly errorprone and the data was often inaccurate.
Another fix in here is the games refreshing at half the rate as it should've been. Things were taking 30 seconds instead of 15 to rotate.

Use overview data for everything, fix rendering refresh rate

---

renderers/bases.py
renderers/inning.py
renderers/outs.py
renderers/pitches.py
renderers/scoreboard.py
renderers/teams.py
utils.py

A previous PR included moving the pixel coordinates out to another file but I'll tackle that later. This is just splitting up the scoreboard renderer into smaller ones that do one thing.
Thought about adding debug strings to each of them but it didn't seem necessary at the moment as their behavior is very simple.

Split out scoreboard renderer into separate renderers

---

README.md
data/scoreboard_config.py

A simple change that allows for a user to specify a single Float for rotate_rates instead of a Dict. This will set all screens to that value.

Accept a Float for rotate_rates to set all screens

---

README.md
config.json.example
data/scoreboard_config.py
renderers/games.py

Add a config option (default is true) to keep the scoreboard pinned to your preferred team while that team is currently in warmup, live or in "game over" status (which seems to last for about 5 minutes after the game ends).
Closes #21 (We can create a new issue to allow us to stay on the final scoreboard for a set amount of time)

Keep scoreboard locked on the preferred team when that game is live

---

config.json.example
data/scoreboard_config.py
main.py

If there are no games for the day, display the current standings instead. Turn this off with the "display_standings_on_offday" config option.
Closes #73

Add option to display standings on an offday.

---

README.md
config.json.example
data/scoreboard_config.py
main.py

Closes #52 
I chose midnight as the default because that is how the scoreboard operates currently.

Add config option to change the end of day time

---

data/data.py

Currenly after 5 retries, the 5 retries just start over again on the same game. If we have rotate on, we should check the next game to see if we have issues downloading that one too.

Error handling fixes

---

data/pregame.py
data/scoreboard.py
data/scoreboard_config.py
renderers/final.py
renderers/offday.py
renderers/pregame.py

Python recommends using the .format() method and we had a combination of both in various spots of our code. Conform them all to the recommended method.

Refactor string formatters

---

ledcoords/README.md
renderers/final.py
renderers/main.py
renderers/pregame.py
renderers/scrollingtext.py

The "width" attribute of "scrolling_text" is no longer unused.

Support for scrolling text width.

---

renderers/main.py

This fixes an issue where the winning and losing pitchers right after a game ends show up as `Unknown`. This will check if the game is over and the winning pitcher is `Unknown` and then update the main `games` object so we get updated winning/losing pitcher status right away.

Update games on final

---

data/data.py
renderers/main.py

When we update the master games list, we'll also try and update the date for the day. If the `end_of_day` has passed, we can move on to the next day. This alleviates the need to reboot the scoreboard in order to get the current date to start showing.
Closes #115

Update the date after 'end_of_day' has expired

---

README.md
utils.py

This is necessary to support the U-mapper and rotation functions from the rpi-rgb-led-matrix library. I based it on the samplebase.py from the library. This allows users to rotate and flip portions of their panel, in my case, it allows me to support a 64x64 matrix from two chained 32x64 matrices.

Add --led-pixel-mapper to support rotation and U-mapper

---

ledcoords/w128h32.json.example
ledcoords/w32h32.json.example
ledcoords/w64h32.json.example
renderers/standings.py

Using the same name for both the stat title and the actual stat was a little confusing. Changed the stat title to actually be `stat_title` instead.

Fix duplicate stat keys

---

data/layout.py
ledcoords/w128h32.json.example
ledcoords/w32h32.json.example
ledcoords/w64h32.json.example

The default font_name shouldn't only be hard coded. Added a defaults key to the layout JSON that can be used to set the default font to something different than the hard coded 4x6.

Add defaults key to layout json for defining a default font

---

main.py
utils.py

When we updated the matrix library we didn't take into account that it would need to be recompiled during update. This should check if the library isn't up to date and give a subtle warning instead of a hard crash if it has not. Most people won't need to update the library anyways.

Added some error checking in case the matrix library wasn't recompiled

---

data/scoreboard.py
data/status.py
ledcolors/scoreboard.json.example
ledcoords/w128h32.json.example
ledcoords/w32h32.json.example
ledcoords/w64h32.json.example
renderers/main.py
renderers/scrollingtext.py
renderers/status.py

Needs some more testing with other statuses. This worked great with the Suspended game but I'm not positive which status types get the `reason` or `notes` field populated.
This **should** cover any case where a `notes` attribute exists on an irregular status that would normally just display the status under the teams. If `notes` exists, it will scroll that. If it doesn't, we check for `reason` and scroll that instread. If neither exists, it should fall back on the normal status screen with no scrolling text.
Closes #165

Add notes or reason to the status screens

---

renderers/teams.py

This should fix a crash that happened if you left out the `"home"` key from your custom team colors json.

Team colors shouldn't require a home key

---

README.md
config.json.example
data/data.py
data/scoreboard_config.py
renderers/main.py
renderers/standings.py

Adds the ability to use an array of strings as the `preferred_teams` and `preferred_divisions` in the config.
`preferred_divisions` will rotate through those divisions when displaying standings.
`preferred_teams` will use the first element as the "favorite" team and will act as it always has before this. A new option in `rotation` called `only_preferred` will limit the rotated games to only games that include teams in the `preferred_teams` list.
Closes #126 
Closes #113

Multiple teams and divisions

---

renderers/main.py

When I updated all the statuses, I removed everything but the live scoreboard from the `static` definition (since we can scroll text on nearly every game state). This broke our old check (which was already a little broken) so I think this should fix it for good now.

Fix the irregular status games

---

data/headlines.py
main.py

When an "important date" was too far away, the news ticker would crash. This should take care of that.
Fixes #252

Fix a crash with the news ticker

---

README.md
config.json.example
data/data.py
data/pregame.py
data/scoreboard_config.py
debug.py
renderers/main.py
renderers/offday.py

Added the `"time_format"` option to the config file so you can specify `"12h"` or `"24h"` for your preferred time output format.
Closes #253

Add 24h time format option to config

---

renderers/status.py

This may fix #261 (and various other scoreboard hangs that haven't been reported here but mentioned on our discord). We're always expecting to get a number returned from this method for updating our scrolling position so we should be returning 0 if there's nothing to scroll.

Fix an issue with scrolling screens when there isn't any reason text

---

data/weather.py

This should fix #260. We should just catch the pyowm exceptions since we aren't specifically using urllib3. I think I proactively added those other exceptions without importing anything so whoops.

Just catch the pwowm connection exceptions since we aren't using urllib3

---

data/data.py

#88 Check for multiple games for a team in a given day and then do is_live check when getting current index for a team

Prioritize live games when there is a multi header

---

data/data.py

This closes #274, caused by attempting to decrement `attempts_remaining` before definition.
The `__game_index_for()` function was the only function that defined `retries` instead of `attempts_remaining`, so renamed that variable for consistency.

Define attempts_remaining instead of retries

---

README.md
data/data.py
main.py
renderers/main.py
renderers/standings.py

Closes #290.
Updates the `rpi-rgp-led-matrix` submodule to latest master to provide better support for Raspberry Pi 4.
This should continue to work for Pi 3 and under without a reinstall. Re-running the installer with `sh install.sh` should now grab the latest in the driver submodule before installing it, and I've tested this to correctly update on an install with the old [submodule @ 36a4633](https://github.com/hzeller/rpi-rgb-led-matrix/tree/36a46331e300764a79a4ba45d723270e8cceedda).

Update submodule to latest master

---

install.sh

feedparser 6.0.0 no longer supports python2. pinning to version < 6 until master is compatible with python3.
would resolve #299

pin feedparser to <6.0.0

---

data/standings.py

Addresses #320
Same test from issue, using new implementation:
```python
if __name__ == '__main__':
standings = Standings.fetch(2021, 4, 14)
for division in standings.divisions:
print('-------')
print(division.name)
print('-------')
for team in division.teams:
team_string = '{name} (W: {w}, L: {l})'.format(name = team.name, w = team.w, l = team.l)
print(team_string)
print('\n')
```
```
-------
AL West
-------
Los Angeles Angels (W: 7, L: 5)
Houston Astros (W: 6, L: 5)
Seattle Mariners (W: 6, L: 5)
Oakland Athletics (W: 5, L: 7)
Texas Rangers (W: 4, L: 7)
-------
AL East
-------
Boston Red Sox (W: 9, L: 3)
Toronto Blue Jays (W: 6, L: 6)
Baltimore Orioles (W: 5, L: 6)
Tampa Bay Rays (W: 5, L: 6)
New York Yankees (W: 5, L: 7)
-------
AL Central
-------
Cleveland Indians (W: 6, L: 4)
Kansas …
```

Refactor standings module for correct win/loss record

---

renderers/main.py
renderers/status.py

Addresses #303 & #258 for scrolling status text.
This _should_ work on all board sizes since it relies on canvas width (tested on 64x32). Might need to add to the `ledcoords` config to customize width of the scroll?

Allow StatusRenderer to support multiple text scrolling

---

README.md
config.json.example
data/config/__init__.py
data/game.py
renderers/games/teams.py
renderers/main.py

If Runs or Hits > 9 (double digits) then truncate the long team name for the display so they don't overflow each other.  There is probably a better way of fixing this.

Truncate team name if Runs or Hits > 9

---

config.json.example
data/config/__init__.py
data/game.py
data/scoreboard/pregame.py
renderers/games/pregame.py
renderers/main.py

Added pregame weather.  In config.json must add `"pregame_weather": true,` note that pregame weather appears to be entered manually when the booth crew shows up.  For tonight's yankees game the api populated around 3pm today for a 7:05 start.

Add pregame weather

---

utils.py

From issue [#396](https://github.com/MLB-LED-Scoreboard/mlb-led-scoreboard/issues/396). Added missing line to set `--led-scan-mode` value from argument flag to `RGBMatrixOptions` property.

Set led-scan-mode arg value

---

data/game.py
data/schedule.py
data/scoreboard/postgame.py
data/scoreboard/pregame.py
renderers/games/postgame.py
renderers/games/pregame.py
renderers/main.py
requirements.txt
version.py

Based on a PR I did for MLB-StatsAPI last year: https://github.com/toddrob99/MLB-StatsAPI/pull/95
Adds text like "HOU leads 2-0", or "Series tied 1-1" to the end of the scroll (after the weather for pregame, after the save pitcher for postgame).
Requires MLB-StatsAPI version 1.6 or higher

Add series status to pre/postgame scroll during playoffs

---

data/game.py

Dumb copy/paste error made it so the home team pitch count would always be 0

Fix pitch count for home team

---

data/__init__.py
data/pitches.py
data/status.py
tests/test_data_up_to_date.py

Subsumes #448
The pitches, teams, and status files all store data from the API, but that we don't want to re-fetch (either to avoid network issues, or to allow customization, or because we need it in a certain format). 
This PR updates:
- Pitches
- Added Sweeper
- Removed "Slutter"
- Updated Slurve abbreviation to SV
- Statuses
- Removed unused statuses (mostly things like "Darkness")
- Added new statuses (mostly COVID-19 related, one related to shift violations) 
And adds one test file which asserts that our data matches the API results in certain ways. This required a slightly change to `data/__init__.py` since we were transitively importing `driver`, which triggered the `argparse` logic and broke the testing framework.

Update stored API data, test to keep up to date

---

renderers/games/teams.py

Currently working on a 64x32 layout that uses the 5x7 font a lot more. Needed a way to specify a specific number of characters to allow for the team name (instead of just going to the short 3 character names). This will allow you to add a `truncate` key to the `teams.name.home` or `teams.name.away` key-paths in your coordinates file to specify a truncate length. If the key isn't found, it falls back to the previous default of 13 characters.

Add the ability to truncate team names to a desired length

---

.github/workflows/require_release_branch.yml
CONTRIBUTING.md
PULL_REQUEST_TEMPLATE.md

Ironically this PR needs to be pointed to master 🙃
This PR will add the workflow to prevent non `dev` branch merges to master. This workflow will be added as a branch protection rule for master, which can be overridden with specific permissions if there's an emergency fix required.
Should cut down on instances of accidental merges to master and will let contributors have better visibility into where they should branch from

Workflow to require release branch to merge to master

---

README.md
config.json.example
data/__init__.py
data/config/__init__.py
data/schedule.py
data/screens.py
data/standings.py
main.py
renderers/main.py

This allows you to have `no_games_live` set for the news and weather screen, just like the current setting for standings.
If both are set, it will rotate between the two every couple minutes until games become live. 
This is accomplished with a kind of clever system where we can pass in conditions from the outside which control how long each screen is shown for.  This also starts to pave the way for a better overall rotation config. I'd love to eventually allow you to have a rotation which looks like this:
```
offday: [news]                                           # options: news, standings
no_games_live: [news, standings]                         # options: news, standings
gameday: [preferred_teams, news, standings, live_games]  # options: preferred_teams (never rotate during these …
```

Allow news ticker when no games are live

---

requirements.txt

Resolves #463
Emulator diff available here
https://github.com/ty-porter/RGBMatrixEmulator/commit/4e85981026deebabf548daf7e887696f7b5ef22b

Bump RGBME to 0.8.4

---

data/schedule.py
data/status.py

I think this might fix #466, but I have yet to witness the issue on my own hardware so I can't fully recreate it.
A few tweaks:
1. Completed games are no longer considered "live" (we have a separate "fresh" status for them, anyway)
2. The `current_idx` is now updated if the list of games got shorter in a refresh
3. `_game_index_for_preferred_team` no longer returns `current_idx` if it fails to find a preferred game - it returns `-1`
4. Removed a flag which was set when the 'preferred game' ended (which almost certainly didn't do the right thing during double headers, anyway)
Number 3 above is the cause of the issue @ty-porter noted on discord with a game being labelled as 'preferred' when it never should have been. Any of them could cause #466, IMO.

Clean up schedule advancement logic

---

data/schedule.py

This should fix #466 (for real this time almost certainly).
`self._games` should have been `games` to avoid re-using from previous refresh

Fix re-using prior refresh of games in certain settings

---

coordinates/w128h32.json.example
coordinates/w128h64.json.example
coordinates/w192h64.json.example
coordinates/w32h32.json.example
coordinates/w64h32.json.example
coordinates/w64h64.json.example
data/game.py
data/scoreboard/__init__.py
data/scoreboard/team.py
renderers/games/teams.py

Addresses #485
Still undergoing testing. This adds the layout keys needed to render the team record on the game screen. By default, the record will render off screen since it takes up quite a bit of space (8 max):
```
(WWW-LL)
12345678
```
Requested behavior can be achieved with a custom coordinates file and the following config setting:
```
"full_team_names": false
```
Future enhancements may need to specify smaller font sizes to fit in smaller

Add option to display team record on game screen

---

data/config/layout.py
renderers/games/teams.py
version.py

Release v6.4.1

---

main.py
renderers/offday.py
requirements.txt

Disable Pillow until upgrade path can be found

---

.git-config-template
.gitattributes
.gitignore
README.md
install.sh

This should fix the issue we're having with newer rasbians which have the `EXTERNALLY_MANAGED` pip setting enabled.
- Sets up a virtual environment
- Installs all dependencies there instead
- Adds a shebang to `main.py` which means you don't need to activate it every time. Instead of `python3 main.py`, you can just run `./main.py` now (not sure if this is great, since we can't gitignore the change it makes, but it's probably fine?)

Add virtual environment to install.sh

---

.github/workflows/run_unittest_on_pr_open.yml
README.md
main.py
renderers/offday.py
requirements.txt

Remove Pillow patch, require Pillow > 10.0.1

---

install.sh

Some distros (including dietpi) do not have make installed by default.  Added command to install make if RGBmatrix is being installed.

Added apt command to install make

---

README.md
utils.py

https://github.com/hzeller/rpi-rgb-led-matrix/tree/master/bindings/python#user
The matrix drops privileges from `root` to `daemon` after it starts up. This is causing all kinds of issues where the `daemon` user seemingly doesn't have read permissions on a lot of different files. It's also recommended to use absolute paths (fixed in #519 already)
Main symptom this works around is not being able to find a cert from `certifi` in the new virtual environment, causing the scoreboard to crash on startup
I tried tweaking permissions on `venv/*` but did not seem to have an effect. It's likely still a pathing issue that would be difficult to work around.
Others are noting similar issues in Pi OS Bookworm so we don't seem to be alone here.
https://github.com/hzeller/rpi-rgb-led-matrix/issues/1607

Do not drop root privilege when running in venv

---

install.sh

Add blacklist snd_bcm2835 module to installer... Should only trigger if they are installing the rgbmatrix libs (so skipped for emulator only).

Add blacklist snd_bcm2835 module to installer

---

data/scoreboard/postgame.py
data/scoreboard/pregame.py

I think this was caused by some weirdness, but my board entered a boot loop earlier because a pitcher existed but didn't have a full name. The places we use this already have safe default values, so this just makes sure they are robust to exceptions.

Fix a crash if pitcher is completely unknown

---

data/scoreboard/postgame.py
data/scoreboard/pregame.py
install.sh
version.py

Release v8.0.1

---

install.sh

Installer now checks debian version, then adds isolcpus=3 to /boot/cmdline.txt or /boot/firmware/cmdline.txt if it does not exist.

Update installer to include isolcpus=3

---

coordinates/README.md
coordinates/w128h32.json.example
coordinates/w128h64.json.example
coordinates/w192h64.json.example
coordinates/w32h32.json.example
coordinates/w64h32.json.example
coordinates/w64h64.json.example
renderers/games/teams.py

Allows capability of relatively positioning the record text against the team name on game screens

Relative team records positioning

---

README.md
install.sh

Allow selection of driver version and set 14ab2ff as current default

---

install.sh

Fixe the missing ! in the check for soundcard blacklist file.
Added install of gcc and g++ to the existing make install for RGB Matrix in install script.
Verified the current published branch works on dietpi with these changes.

Fixed missing ! for snd blacklist and added g++ and gcc for DietPi

---

.github/workflows/run_unittest_on_pr_open.yml
README.md
requirements.txt
tests/test_validate_config.py

Removes support for 3.8, adds 3.12 and 3.13
Includes `setuptools` and `legacy-cgi` due to dependencies in `pyowm` and `feedparser` that do not have recent releases.
With new raw string syntax, updated a test that was throwing warnings.

Remove tests for deprecated Pythons, remove from README pill

---

requirements.txt

`feedparser` actually works on Python 3.13 assuming we're at 6.0.11 or higher

Bump feedparser to 6.0.11

---

data/game.py
data/schedule.py
data/teams.py
tests/test_data_up_to_date.py

Fixes #574
This still allows customization in teams.py, but uses the same data as before #556 if the id isn't found, like is common in exhibition games

 Fall back to API data when team ID not recognized 

---

renderers/scrollingtext.py

We were already doing this to the left, but it's useful if we also do it on the right both to minimize what we're trying to draw but also to allow different scrolling texts to appear on the same horizontal line as each other.
After this PR, a scrolling text element only needs one character's width of empty space on either side of it. Here's a modified version of the homepage where I made these 'dead' zones visible:
Compare this to the current behavior:
I think this makes something like #547 much easier in the different possible layout options because it matters much less what order things will be drawn

Optimize scrolling text by trimming on both sides

---

coordinates/w128h32.json.example
coordinates/w128h64.json.example
coordinates/w192h64.json.example
coordinates/w32h32.json.example
coordinates/w64h32.json.example
coordinates/w64h64.json.example
renderers/games/game.py
renderers/main.py

Something I missed in #585. The current code is looping on wherever the loop x position is for the batter name, which is not necessarily a meaningful number here and leads to weird 'hitching' where the text appears to start in the middle during the second loop-around on some screens.

Add independent loop point for due up batters

---

renderers/games/teams.py

`graphics.DrawLine` is more optimized and (on real hardware) should leverage compiled C code for each row in the banner rather than trying to iterate over WxH pixels in Python directly

Refactor team banner draw routine

---

data/scoreboard/team.py

This is why users who didn't restart their boards were observing odd behavior the next day. The underlying team_colors dict was being modified

Fix city connects becoming sticky due to shallow copy

---

README.md
config.example.json
data/config/__init__.py
data/game.py
data/schedule.py
tests/test_game.py

Made the API refresh rate configurable in config.json in number of seconds. Defaults remains 10, it validates INT and wont allow less than 3 seconds so we don't spam the API.

Make API refresh rate configurable v3

---

data/dates.py
data/game.py
data/headers.py
data/standings.py
data/uniforms.py
main.py
tests/test_data_up_to_date.py

Added data.headers with a constant API HEADERS.  Updated the statsapi.game() requests in 
```
data/dates.py
data/game.py
data/standings.py
data/teams.py
data/unifiorms.py
```
Need Brian Ward to take a look at the main game.py requests and replace his `testing_params`
I'm honestly not sure how to test that were actually sending the correct headers

Added ability to set headers on statsapi.game() requests
