MLB-LED-Scoreboard/mlb-led-scoreboard

- renderers/games.py
Use the overview object to get game status. Check again during the regular season to see if the old method gets updated in real time.
> Use the overview object to get game status

- README.md
- config.json.example
- data/pregame.py
- data/scoreboard.py
- data/scoreboard_config.py
- debug.py
- main.py
Added a pretty basic debug logger that can be controls via a json attribute in config.json.
Added debug strings to our data objects.
> Add basic debug logging

- README.md
- data/pregame.py
> Display pregame times in local time zone

- README.md
- config.json.example
- data/scoreboard_config.py
- renderers/games.py
I feel like 0.1 is a very nice refresh rate for the scrolling text. This makes that change and adds a config option for slower Pis (or if you just like the slower refresh rate)
> Speed up the scrolling speed a bit and add a config option

- README.md
- config.json.example
- data/scoreboard_config.py
- renderers/games.py
> Default to waiting for scroll to finishe before rotating

- README.md
- config.json.example
- data/scoreboard_config.py
- renderers/games.py
> Add a rotate_rate option to control how quickly games rotate

- debug.py
- renderers/error.py
- renderers/games.py
- utils.py
> Game id not found

- LICENSE.md
- README.md
> Update License and README

- data/pregame.py
Review and merge for some more info about each pitcher during the pregame scroll.
Currently adds the pitcher's first initial, their current record and current ERA.
> Pregame extra pitcher info

- renderers/games.py
- renderers/status.py
> Handle cancelled games in spring training

- renderers/games.py
> Don't reset scrolling text pos when not rotating games

- LICENSE.md
- README.md
- config.json.example
- data/pregame.py
- data/scoreboard_config.py
- main.py
- renderers/games.py
- renderers/status.py
Merge on 3/15 unless bugs are filed before then.
> Release 1.1.0

- renderers/final.py
- renderers/games.py
> Handle games that were completed early

- renderers/games.py
> Fix rotation for cancelled/delayed/postponed

- data/pregame.py
> Fix issue when a pitcher hasn't recorded an out yet

- main.py
- renderers/offday.py
> Fix end of day, add some debug logs to the offday renderer

- data/status.py
- renderers/games.py
- renderers/pregame.py
- renderers/status.py
Closes #110
Closes #112 
Also extract statuses out to their own class with some friendly methods
> Handle manager challenges and delayed start

- README.md
- config.json.example
- data/scoreboard_config.py
- renderers/final.py
- renderers/games.py
- renderers/scoreboard.py
- renderers/status.py
- renderers/teams.py
> Add option to choose between team abbreviations and full names

- README.md
- data/scoreboard_config.py
- main.py
Closes #90 
Also this config option was completely missing from the README
> Allow display standings on offday for preferred team

- debug.py
- main.py
> Add basic script info when script starts

- data/final.py
- renderers/final.py
> Add saving pitcher information to the post game scroll

- README.md
- utils.py
> Update rgbmatrix submodule

- data/data.py
- main.py
- renderers/standings.py
See #117 
Pretty much just wrapping the standings code in a class and simplifying the function params.
> Refactor the standings code

- README.md
- install.sh
> Automate software installation

- README.md
- utils.py
> Update rgbmatrix submodule for new multiplex mappers

- data/status.py
- renderers/status.py
> Handle suspended games

- main.py
- renderers/status.py
Fix a small alignment issue on 32x32 screens during a "delayed start" game
> Release 1.6.1

- data/pregame.py
> Fix ERA to always display 2 digits after the decimal

- ledcoords/w128h32.json.example
Update a few coordinates for pregame and standings.
> Updated standings and pregame coordinates for 128x32

- data/data.py
Rotation was a little broken. This should actually advance us now.
> Actually advance when we're mid-inning

- data/weather.py
- ledcoords/w128h64.json.example
- main.py
Fixes the couple of issues that slipped through the cracks
> Fixes for #210 and #211

- ledcoords/w128h64.json.example
@phonorad does this look correct?
> 128x64 layout update

- data/weather.py
We should gracefully fail and try again later when we have a connection issue fetching weather.
> Exception handling for weather connection issues

- install.sh
- main.py
Adding -n argument to skip config.json file set up. This allows for easier updates via ssh and shortcuts.
previous PR forgot to version bump to 3.1.3
> Adding -n argument to install script

- README.md
- data/data.py
Fix a typo in an attribute that tried to fetch the perfect game layout.
> Fix perfect layout

- data/status.py
- renderers/status.py
Pulled all the statuses from https://statsapi.mlb.com/api/v1/gameStatus and added them to our status data object.
> Add every status that MLB recognises to our status data

- data/data.py
- main.py
> Fix preferred team offday check

- data/data.py
The old filters weren't working and I have updated them to use a more pythonic, efficient filter. I saw that the last update fixed the off day filter but used enumerate and didn't do anything to the "only show preferred teams" filter.
> Use Pythonic Filters

- data/data.py
- ledcolors/scoreboard.json.example
- ledcoords/w128h32.json.example
- ledcoords/w128h64.json.example
- ledcoords/w32h32.json.example
- ledcoords/w64h32.json.example
- renderers/final.py
- renderers/network.py
- renderers/offday.py
- renderers/pregame.py
- renderers/scoreboard.py
- renderers/standings.py
- renderers/status.py
- Expanded and enhanced the error logging for network issues
- Catching networking errors in newly merged double header code
- Added a network issues indicator that should show up on the scoreboard when a networking issue is encountered
> Add network indicator

- data/dates.py
- data/headlines.py
- main.py
- Fix the RSS feed URLs for MLBs official news. (fixes #275)
- Update the spring training dates for 2020
> Fix rss feeds

- data/data.py
- renderers/main.py
- renderers/standings.py
Fixing issue #228 by filling in the last two rows to match the rest of the background.
Also adding some standings render exception logging and the ability to view standings when setting a demo date
> 228 standings fix

- install.sh
> Lock feedparser < 6.0.0

- install.sh
> Fix config copy in installer

- renderers/games/teams.py
Fixes abbreviation bug and documents nested conditionals for using team full names
> Team abbreviation patch

- data/pitches.py
> Updated list of long and short pitch types

- data/pitches.py
- data/scoreboard/pitches.py
In case a pitch is missing from the list, fall back to the correct unknown pitch text for the configured pitch display
> Add fallback for missing pitches

- install.sh
> Fix config permissions when created by installer

- data/__init__.py
- data/game.py
- data/schedule.py
- data/scoreboard/pregame.py
- install.sh
- renderers/games/pregame.py
> Show national broadcasts during pregame

- README.md
- coordinates/README.md
Formatting cleanup for all the config changes
I also resized all the images to 200px high and auto-width, then tried to arrange for a bit more symmetry.
> Clean up README

- data/scoreboard/pitches.py
- renderers/games/game.py
Typo introduced by me in #431 prevented pitch speed from rendering if it was set to "short" descriptions
> Fix short pitch count display

- README.md
- config.json.example
- data/__init__.py
- data/config/__init__.py
- data/delay_buffer.py
- data/game.py
- data/schedule.py
Closes #439.
This is the first implementation, might need a few iterations. 
The basic idea is to use something kind of like a [ring buffer](https://en.wikipedia.org/wiki/Circular_buffer) for game updates, but one that has non-destructive reads. 
This means that the first update (like when a game is first selected for display on start or when coming back from the rotation of other games from a inning break) happens in real time. But the second update is just added to the queue, and this update won't become the "live" displayed data until after the buffer is full and overwrites the first data that was fetched. 
For a ring buffer of size 5, this will mean (5 -1) * (10 seconds/update) = 40 seconds of delay, which was what I needed to sync a stream of the Mets-Marlins game nearly perfectly in …
> Add ability to buffer game updates for syncing with TV

- data/game.py
- main.py
> Add statsapi version checks, make from_schedule safer

- data/config/__init__.py
> Better validation for delay timing

- README.md
- config.json.example
- coordinates/README.md
- data/__init__.py
- data/config/__init__.py
- data/delay_buffer.py
- data/game.py
- data/pitches.py
- data/schedule.py
- data/status.py
- main.py
- tests/test_data_up_to_date.py
See #442 for notes on buffering/delaying game updates
> Release 6.2.0

- renderers/games/teams.py
Reverts MLB-LED-Scoreboard/mlb-led-scoreboard#456, will repoint it back to dev for 6.2.1 release branch
> Revert "Add the ability to truncate team names to a desired length"

- renderers/games/teams.py
Repeat of #456 pointed to dev for 6.2.1 release
> Truncate team names

- data/config/__init__.py
- data/headlines.py
- data/scoreboard/pregame.py
- data/time.py
- renderers/offday.py
> Handle missing headline keys, fix Windows emulated clock format

- data/config/__init__.py
- data/headlines.py
- data/scoreboard/pregame.py
- data/time.py
- renderers/offday.py
> Release v6.3.3

- README.md
> Fix wiki link in readme

- README.md
- colors/scoreboard.json.example
- coordinates/README.md
- coordinates/w128h32.json.example
- coordinates/w128h64.json.example
- coordinates/w192h64.json.example
- coordinates/w32h32.json.example
- coordinates/w64h32.json.example
- coordinates/w64h64.json.example
- data/plays.py
- data/scoreboard/__init__.py
- renderers/games/game.py
- renderers/main.py
- tests/test_data_up_to_date.py
- version.py
> Release v6.5.0

- README.md
- coordinates/README.md
Added documentation for enabling and modifying play results.
> Added play result documentation to readme and config/readme

- .github/workflows/run_unittest_on_pr_open.yml
> Run tests against Python 3.11 in CI

- main.py
- renderers/offday.py
- requirements.txt
- version.py
> Release v7.0.0

- data/weather.py
- main.py
- renderers/offday.py
- version.py
> Use fully-qualified asset path for logo

- install.sh
> added check for osx bsd style sed in installer

- data/teams.py
> Athletics are no longer in Oakland

- data/schedule.py
I'm not sure why we are currently doing what we do, but I believe it is wrong and causing issues https://github.com/MLB-LED-Scoreboard/mlb-led-scoreboard/discussions/558
> Fix offday calculation

- install.sh
> Move rpi-rgb-led-matrix version to master

- requirements.txt
> Avoid broken 0.12.3 RGBME version

- data/__init__.py
- data/schedule.py
- main.py
- renderers/main.py
This tries to better document the logic around game rotation, and hopefully fix a reported bug where it would get stuck.
> Clean up should_rotate logic

- .gitignore
- debug.py
- install.sh
> Add logfiles and set exit conditions in installer

- install.sh
- version.py
> Allow installer to proceed if submodules/matrix already exists

- install.sh
- version.py
> Release v8.2.3

- data/config/__init__.py
- tests/fixtures/config.json
- tests/test_validate_config.py
- validate_config.py
> Remove deprecated rotation rate fix

- data/scoreboard/team.py
- renderers/games/teams.py
- version.py
> Release v8.3.1

- renderers/games/teams.py
> Cast color tuple to graphics.Color object before using in graphics.DrawLine

- version.py
> Release v8.3.2

- main.py
- tests/fixtures/config.example.json
- tests/fixtures/config.json
- tests/test_validate_config.py
- validate_config.py
> Add renaming to config validation
